image: maven

stages: # List of stages for jobs, and their order of execution
  - test
  - build
  - publish

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn clean test

package:
  stage: build
  script:
    - mvn package

pages:
  stage: publish
  only:
    - master
  image: ruby:2.7
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
    - cp -R target/apidocs public
  artifacts:
    paths:
      - public
